COMMENT =			Luke Smith's fork of the suckless terminal
V = 				0.8.5
DISTNAME =			st-luke-${V}
CATEGORIES =		x11
REVISION =			0

HOMEPAGE =			https://github.com/lukesmithxyz/st
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# MIT
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =		lukesmithxyz
GH_PROJECT =		st
GH_COMMIT =			master

.include			<bsd.port.mk>