COMMENT =			Luke Smith's fork of the suckless window manager
V = 				6.2
DISTNAME =			dwm-luke-${V}
CATEGORIES =		x11

HOMEPAGE =			https://github.com/lukesmithxyz/dwm
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# MIT
PERMIT_PACKAGE =	Yes

GMAKE =				/usr/local/bin/gmake

GH_ACCOUNT =		lukesmithxyz
GH_PROJECT =		dwm
GH_COMMIT =			master

.include			<bsd.port.mk>