COMMENT =			List block devices
V = 				1.0
DISTNAME =			lsblk-${V}
CATEGORIES =		sysutils

HOMEPAGE =			https://github.com/RHL120/openbsd_lsblk
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# GPLv3
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =		swindlesmccoop
GH_PROJECT =		openbsd_lsblk
GH_COMMIT =			c196aa3c331a930e3ae8078b43fc5dca73f9e373

.include			<bsd.port.mk>