COMMENT =			Luke Smith's fork of the suckless dynamic menu
V = 				5.0
DISTNAME =			dmenu-luke-${V}
CATEGORIES =		x11
REVISION =			0

HOMEPAGE =			https://github.com/lukesmithxyz/dmenu
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# MIT
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =		lukesmithxyz
GH_PROJECT =		dmenu
GH_COMMIT =			c1819f18c07df6984bbfd2ca7207295eec85806f

.include			<bsd.port.mk>