COMMENT =			Luke Smith's fork of the suckless dynamic menu
V = 				5.0
DISTNAME =			dmenu-luke-${V}
CATEGORIES =		x11
REVISION =			0

HOMEPAGE =			https://github.com/lukesmithxyz/dmenu
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# MIT
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =		lukesmithxyz
GH_PROJECT =		dmenu
GH_COMMIT =			705b3c7c9f74fd1c370c6ed994e821135bb7acd4

.include			<bsd.port.mk>