COMMENT =			A simple xdg-open replacement
V = 				1.0
DISTNAME =			tao-${V}
CATEGORIES =		sysutils

HOMEPAGE =			https://github.com/wooosh/tao/
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# GPLv3
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =		swindlesmccoop
GH_PROJECT =		tao
GH_COMMIT =			cee12b747dd362e324d8bc55482da179638b4707

WANT_LIB =			magic
CC =				egcc

.include			<bsd.port.mk>