COMMENT =			Simple and fast TUI file manager with no dependencies
V = 				0.6.7
DISTNAME =			cfm-${V}
CATEGORIES =		sysutils

HOMEPAGE =			https://eccles.dev/cfm/
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# MPLv2
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =		swindlesmccoop
GH_PROJECT =		cfm-openbsd
GH_COMMIT =			ddfeb886b980f19d56288fc4531a73b3b724ad3b

.include			<bsd.port.mk>