COMMENT =			Swindles McCoop's fork of the suckless window manager
V = 				6.2
DISTNAME =			dwm-swindles-${V}
CATEGORIES =		x11

HOMEPAGE =			https://git.cbps.xyz/swindlesmccoop/dwm
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# MIT
PERMIT_PACKAGE =	Yes

GMAKE =				/usr/local/bin/gmake
USE_GMAKE =			yes

CONFIGURE_SCRIPT =	configure
CONFIGURE_STYLE =	simple

GH_ACCOUNT =		swindlesmccoop
GH_PROJECT =		dwm
GH_COMMIT =			9951fc39afb70b32f55b7f9fc2a0bc0b31eec823

.include			<bsd.port.mk>