COMMENT =			ISC licensed reimplementation of the GNU util
V =					3.0
DISTNAME =			shuf-${V}
CATEGORIES =		sysutils
REVISION =			0

HOMEPAGE =			https://github.com/ibara/shuf
MAINTAINER =		Swindles McCoop <swindlesmccoop@waifu.club>

# ISC
PERMIT_PACKAGE = 	Yes

CONFIGURE_SCRIPT =	configure
CONFIGURE_STYLE =	simple

MASTER_SITES =		https://github.com/ibara/shuf/releases/download/${DISTNAME}/

.include			<bsd.port.mk>